# Generated by Django 5.0.3 on 2024-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognom1', models.CharField(max_length=50)),
                ('cognom2', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('curs', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('Alumnat', 'Alumnat'), ('Professorat', 'Professorat')], max_length=20)),
            ],
        ),
    ]
